spring:
  application:
    name: velaris-core

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOG_LEVEL}
    org.springframework.security: WARN
    com.velaris: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

security:
  public-endpoints: >
    /api/auth/**,
    /swagger-ui/**,
    /v3/api-docs/**,
    /actuator/health

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS}

management:
  endpoints:
    web:
      exposure:
        include: health,info